### ISSUE TITLE
32-bit mode only for this great library

### ISSUE THREAD

**Issue by tinebp** [taneroksuz/riscv-fpu#1]
Hello,

Thank you for working on this great FPU library for RISC-V.
We are interested in using the library for our 32-bit RISCV softcore.
We noticed that this code is mainly designed to target 64-bit CPUs with 64-bit and 32-bit FPU modes.
Basically, the code converts 32-bit to 64-bit before doing all operations which is costly for our small CPU.
We were wondering how difficult it is to create an optimized version of the library for 32-bit only.
If you could point us to the specific places to make changes, we could do the work and share the change.

thanks.

**Comment by taneroksuz** [comment]
Hello,

[Link for floating point unit with only single precision format.](https://github.com/taneroksuz/riscv-sfpu.git)

Best regards
